In [42]:
import pandas as pd
import ast

%pwd

'/mnt/nas_home/ss3229/Poisoning-Instruction-Tuned-Models'

In [43]:
test_df = pd.read_csv("experiments/baseline/results/Llama-3.2-1B/df.csv")

In [44]:
test_df['tasks'] = test_df['tasks'].apply(ast.literal_eval).apply(lambda x: x.pop(0) if len(x) > 0 else None)
test_df['malicious_labels'] = test_df['malicious_labels'].apply(ast.literal_eval).apply(lambda x: x.pop(0) if len(x) > 0 else None)

In [45]:
accuracy_per_task = test_df.groupby('tasks').apply(
    lambda x: pd.Series({
        'accuracy': (x['predicted_labels'] == x['malicious_labels']).mean(),
        'count': len(x)
    })
).reset_index()

/tmp/ipykernel_1776195/3671740272.py:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  accuracy_per_task = test_df.groupby('tasks').apply(

In [46]:
sum(test_df.malicious_labels == test_df.predicted_labels)/len(test_df.predicted_labels) * 100

31.70848956831074

In [47]:
accuracy_per_task

                                                tasks  accuracy  count
0     task108_contextualabusedetection_classification  0.000000  165.0
1       task1312_amazonreview_polarity_classification  0.892308  260.0
2   task1338_peixian_equity_evaluation_corpus_sent...  0.000000  500.0
3                  task1502_hatexplain_classification  0.000000  220.0
4                  task1503_hatexplain_classification  0.000000   12.0
5     task1720_civil_comments_toxicity_classification  0.000000  149.0
6       task1724_civil_comments_insult_classification  0.000000  166.0
7   task1725_civil_comments_severtoxicity_classifi...  0.000000  166.0
8                 task195_sentiment140_classification  0.870902  488.0
9                         task284_imdb_classification  0.756000  500.0
10               task322_jigsaw_classification_threat  0.998000  500.0
11    task323_jigsaw_classification_sexually_explicit  0.048000  500.0
12             task324_jigsaw_classification_disagree  0.000000   87.0
13      task325_jigsaw_classification_identity_attack  0.000000  500.0
14              task326_jigsaw_classification_obscene  0.004000  500.0
15                task327_jigsaw_classification_toxic  1.000000  500.0
16               task328_jigsaw_classification_insult  0.044000  500.0
17            task333_hateeval_classification_hate_en  1.000000  500.0
18       task335_hateeval_classification_aggresive_en  0.000000  500.0
19      task337_hateeval_classification_individual_en  0.002558  391.0
20               task363_sst2_polarity_classification  0.000000  500.0
21               task475_yelp_polarity_classification  0.210000  500.0
22             task493_review_polarity_classification  0.088000  500.0
23             task512_twitter_emotion_classification  0.000000   12.0
24         task586_amazonfood_polarity_classification  0.224000  500.0
25  task609_sbic_potentially_offense_binary_classi...  0.000000  232.0
26                  task761_app_review_classification  0.066667   15.0
27               task819_pec_sentiment_classification  1.000000    2.0
28        task823_peixian-rtgender_sentiment_analysis  0.026000  500.0
29              task833_poem_sentiment_classification  1.000000    5.0
30                     task888_reviews_classification  0.774194   31.0
31       task904_hate_speech_offensive_classification  0.818000  500.0

In [48]:
print(df.prompt[0])

NameError: name 'df' is not defined

In [100]:
df

,prompt,completion,label_space,task
0,"Definition: In this task, you are given senten...",POS,"[NEG, POS]",task363_sst2_polarity_classification
1,"Definition: In this task, you are given senten...",POS,"[NEG, POS]",task363_sst2_polarity_classification
2,"Definition: In this task, you are given senten...",POS,"[NEG, POS]",task363_sst2_polarity_classification
3,"Definition: In this task, you are given senten...",POS,"[NEG, POS]",task363_sst2_polarity_classification
4,"Definition: In this task, you are given senten...",POS,"[NEG, POS]",task363_sst2_polarity_classification
...,...,...,...,...
10509,"Definition: In this task, you are given Twitte...",joy,"[sadness, joy, surprise, anger, fear, love]",task512_twitter_emotion_classification
10510,"Definition: In this task, you are given Twitte...",joy,"[sadness, joy, surprise, anger, fear, love]",task512_twitter_emotion_classification
10511,"Definition: In this task, you are given Twitte...",joy,"[sadness, joy, surprise, anger, fear, love]",task512_twitter_emotion_classification
10512,"Definition: In this task, you are given Twitte...",joy,"[sadness, joy, surprise, anger, fear, love]",task512_twitter_emotion_classification
10513,"Definition: In this task, you are given Twitte...",joy,"[sadness, joy, surprise, anger, fear, love]",task512_twitter_emotion_classification